spring.application.name=product-micro-service
server.port=8082
jasypt.encryptor.password=omer_secret_key
spring.datasource.url=jdbc:mysql://localhost:3306/product_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=ENC(RXkujaI1dVER6Mj8BjQzFud/18MgH/RdGpZExaeJM29P2b8fkmxOB+nXUUxlroi5)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml